# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ingredients', models.TextField(verbose_name='ingredients')),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to=b'')),
                ('ts', models.DateTimeField()),
                ('cookTime', models.DurationField()),
                ('source', models.CharField(max_length=64)),
                ('recipeYield', models.IntegerField()),
                ('datePublished', models.DateField(verbose_name='date published')),
                ('prepTime', models.DurationField()),
                ('description', models.TextField()),
            ],
        ),
    ]
